name: My first workflow

on: workflow_dispatch

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
    - name: Running Scripts
      run: |
       pwd
       ls -a
       node -v  

    

       
