name: My first workflow

on: [workflow_dispatch,push]

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Parent Working Directory
        run: pwd

      - name: List Paths
        run: ls -a  

      - name: Node version
        run: node -v  

       
