name: My first workflow

on: workflow_dispatch

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print working directory
        run: pwd

      - name: Create folder one level down
        run: mkdir -p myfolder

      - name: Verify folder created
        run: ls -a

      - name: Create a file inside that folder
        run: echo 'console.log("Hello World");' > myfolder/app.js

      - name: Verify file inside folder
        run: ls -a 

  
