name: My first workflow

on: workflow_dispatch

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print system info
        run: echo "System Information"

      - name: Operating System
        run: uname -s   

      - name: Number of processors
        run: nproc  

      - name: Processor architecture
        run: uname -m  

      - name: All system info
        run: uname -a   
