name: My first workflow

on: workflow_dispatch

jobs:
  my-first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Show Operating System
        run: echo "OS:${{ runner.os }}"

      - name: Show number of processors
        run: echo "Number of processors:$(nproc)"

      - name: Show processor architecture
        run: echo "Processor architecture:$(uname -m)"

      - name: Run Node environment variables
        run: node -e "console.log('Node Version:', process.version); console.log('Platform:', process.platform); console.log('Arch:', process.arch);"
